### ISSUE TITLE
Create a New record to saved duplicate records in the database.

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile#2]
**I attached the blew code.**
   `private void createRyot() {
final OdooValues values = new OdooValues();
 values.put("sb_ac_no", mSbAccount.getText());

             
                values.put("post_code", mPostalCode.getText());

                    values.put("potential_ryot", false);
             
                values.put("section_id", AppUtils.getIntFromFloatString(mSectionMasterList.get(mSection.getSelectedItemPosition()).id));

                client.create("ryot.master", values, new IOdooResponse() {
                    @Override
                    public void onResult(OdooResult result) {
              
                        Toast.makeText(getActivity(), "Saved Successfully", Toast.LENGTH_LONG).show();
                        getActivity().onBackPressed();

                    }

                    @Override
                    public boolean onError(OdooErrorException error) {
                        progresslayout.setVisibility(View.INVISIBLE);
                        return super.onError(error);
                    }
                });
}`

**Comment by bunny-oogbox** [comment]
Hello @cviacmob 
Yes, because you are on Mobile data it take some time and the request get timeout and it retries again.
When creating any record on the server with API call. Just change the retry policy for that request via
```java
client.withRetryPolicy(Integer requestTimeout, Integer maxRetry);
```
and set maxRetry to zero.
Like in your example:
```java
client.withRetryPolicy(50000, 0); // 50 second timeout and no retry if failed.
client.create("ryot.master", values, new IOdooResponse() {
...
...
```
When failed you get error in ``onError`` with ``Timout``

**Comment by bunny-oogbox** [comment]
Reopen issue if your problem not resolved.

Thanks.
