### ISSUE TITLE
Hug Data Loading very slowly 

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile#3]
How to fast data load in server database , 
Example for i load the 3000 records but slowly read the database the blew code.

 ODomain domain = new ODomain();
        domain.add("state", "=", "draft");
        OdooFields fields = new OdooFields();
        fields.addAll("id", "doc_forty_id", "ryot_name", "season_id", "uom_id", "plant_type_id", "ryot_number", "cane_variety_id", "division_id", "crop_type_id", "estimated_setts", "section_name", "plot_name", "setts_type_id", "active",
                "name", "planting_date", "village_name", "display_name", "nursery_fitness_certificate");
        int offset = 0;
        int limit = 100000;
        String sorting = "";
        client.searchRead("doc.forty.for.sdo", null, fields, offset, limit, sorting, new IOdooResponse() {
            @Override
            public void onResult(OdooResult result) {
                OdooRecord[] records = result.getRecords();
                for (OdooRecord record : records) {
             
                }
            }
        });
    }

**Comment by bunny-oogbox** [comment]
duplicate https://github.com/oogbox/odoo-mobile-api/issues/18
